config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Yousaf95/yProv4SQA_UseCase:
      branch: main
      repo: https://github.com/Yousaf95/yProv4SQA_UseCase
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-ecru-bat.sh
        container: qc.acc_nippy-mauve-cheetah
  QC.Doc:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-asparagus-malamute.sh
        container: qc.doc_skanky-copper-dogfish
      github.com/Yousaf95/yProv4SQA_UseCase git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-taupe-ray.sh
        container: qc.doc_lousy-harlequin-cuscus
      github.com/Yousaf95/yProv4SQA_UseCase markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cinnabar-coati.sh
        container: qc.doc_frumpy-cardinal-barnacle
  QC.Lic:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-amethyst-binturong.sh
        container: qc.lic_sloppy-amethyst-paradise
  QC.Sec:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-crimson-quokka.sh
        container: qc.sec_surly-platinum-armadillo
  QC.Sty:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase flake8:
        commands:
        - /usr/bin/env sh .sqa/script.beady-eggplant-uguisu.sh
        container: qc.sty_cozy-cream-scorpion
  QC.Uni:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ready-gold-jaguar.sh
        container: qc.uni_gamy-beige-vulture
  QC.Ver:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cinnabar-mayfly.sh
        container: qc.ver_pasty-peach-mist
timeout: 5400
