config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Yousaf95/yProv4SQA_UseCase:
      branch: main
      repo: https://github.com/Yousaf95/yProv4SQA_UseCase/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-sepia-tiger.sh
        container: qc.acc_queasy-indigo-hamster
  QC.Doc:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-heliotrope-squirrel.sh
        container: qc.doc_lovely-mauve-eleuth
      github.com/Yousaf95/yProv4SQA_UseCase git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-thistle-dane.sh
        container: qc.doc_thirsty-plum-bullfrog
      github.com/Yousaf95/yProv4SQA_UseCase markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-wisteria-akbash.sh
        container: qc.doc_crappy-puce-chow
  QC.Lic:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-orange-cichlid.sh
        container: qc.lic_stinky-malachite-bobcat
  QC.Sec:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-brown-moth.sh
        container: qc.sec_tasty-sangria-macaque
  QC.Sty:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-jade-jackal.sh
        container: qc.sty_beady-chartreuse-warthog
  QC.Uni:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-thistle-rabbit.sh
        container: qc.uni_cranky-lilac-crane
  QC.Ver:
    repos:
      github.com/Yousaf95/yProv4SQA_UseCase get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-blue-oyster.sh
        container: qc.ver_slimy-ochre-moth
timeout: 5400
